// Generated by scripts/build-photos.py. Do not edit by hand.
export const PHOTOS = {
 "operators": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#3b444b",
  "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZwCdACNZzgP5cLxZZk2wAAD8+dE0xdazwS3y8vMQhikOoLVA4KVzd2p47PIcSB+CCQdPMW+XjfvN3xQ9EUS7zVve/XWxSif4pmDbjavc7UuL75HU0zPeeeBriDIq3BrjF+QaL9OI378AAAA=",
  "alt": "Two experienced operators leaning over machinery in a plant, lit by warm window light"
 },
 "hands-valve": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2488,
  "bg": "#3f4a53",
  "lqip": "data:image/webp;base64,UklGRhwBAABXRUJQVlA4IBABAADwBgCdASoYACsAPu1sqFAppiOiqqoBMB2JZwDKAmyLXqGzyCe9OuJMw+SWkzjefnb3YpUXVTsZHFrDkbiTy8SAAP6meW/zQiwCsFcRWhFJTT1cQdZTK/FW3YJRuHXGot2bTmV2aFhb6lD+6D1L3w0YV1qEdokoXTvlqO2BHTkI+K743hFD9Prltpdx2PKV7Oqz1elvU8yCHA1sxXvJI7QS9GsnphzHbdR2HQqrjrcvg2Mvwd4EZakxESnUIurS9U8h5chDsnUsOGBLfOv0SOmChya2ulaC1HYyg8OL+e5Gy5samm7Da/+qFgvynUPJav2lBdA9iAW0FW17/s7ZKPBFpxRk2U7hL+v/vcgaOXgAAA==",
  "alt": "Gloved hands fitting a valve onto a water line"
 },
 "stairway": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2096,
  "bg": "#4b555f",
  "lqip": "data:image/webp;base64,UklGRiIBAABXRUJQVlA4IBYBAADwBgCdASoYACQAPu1srlIppaQiqrgIATAdiWcAxrst+HraJBUtCRR+TrRNlqiW6DZ0q9uS+XPBlS9/nBG1fwGAAPlr225RvxhMrVwIVaME/Mk1tKaqUUUa7dki8Mk4B0Toj5iPhw7XF9U66/aEBtMTvuT/RB9gH/+9A8uhP3qdDSVmCeP8MyNxaYh5N31x2GK+3vlxyX94j+Pi3i7jpVEnYHDSmu7dUAPc+lth36mr4PjqDfHD7iMkQwRZDZI0GZgdSgT9joJTUguYkoQ0xqa5I1Q5eUyDv+Pur8rQTmjRps+hSu1zOJ9UiYYXcp3hGip+OPjKc865GR8YSu9TLJAJowgQiMxAEiAl5eYOEeTiAFWkB/hgAA==",
  "alt": "Looking down a metal stairway onto circular clarifier tanks"
 },
 "outfall": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#4f5b67",
  "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAD5LHZmQwqsPi5+Y4AAP7L5+x0nHMkg8Nm3H2LVhNH8B0ocqDzIdhDXxOtw1DF0AfkypqBAgmLqo1iO16vK80fyfSi4tR5RFmp2pE5yGC1h7bP+OQjQuYci+gWQ+k7ZLj7cZ5YhQUMAAA=",
  "alt": "Treated water pouring from a row of outfall pipes"
 },
 "plant-night": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1335,
  "bg": "#323b43",
  "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwCo9Yuk3q5EB7YONqEgwVS4AP7wxbXMjo3Yx8zLyNbVeFhoxVDjidXrfkBDEF7hI25FBkfiOerfnPKSnKfHWAnKJmuS0IgXDFYnZfjK9aQOEHtbnOHqoJwu8Ae/K/MZxCD0g3LRWrtKurTpCLUFSkGV5Kd+6fOqi7wdmpZPfSR74AA=",
  "alt": "A water treatment plant lit at night, seen from above"
 },
 "plant-fog": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1332,
  "bg": "#677079",
  "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoYABAAPu1kqU2ppaOiMAgBMB2JZwCdACHcIq2jM44eMQHmAAD+6uxVD1nc8LxicdnZX4Eu38yCQbGSmxjfgh7AlP7FUqv/53+r8paqHIpkOxxvRWIimTEfcK/myc/8th3q+RvYAAA=",
  "alt": "Aerial view of a treatment plant with domed tanks in morning mist"
 },
 "plant-bw": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#56626d",
  "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwAFEB7wC5i/Ctzwl2QAAPsFc5R7TwG+FCkqRx+7qxNPMILsJ54aQPymKHxL+03vQPBKZjWlQkuxrKprPUC/pYjter4ONYDt0q1/D2llyYYFO0uXMea/ezTjuJIZnHi0s0rd5I/pwSXmyvNlNPqcUIAAAA==",
  "alt": "Black and white aerial view of a large treatment plant with many circular clarifiers"
 },
 "aerial-rust": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#49535d",
  "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwCw7Yw6yAviQ1FuAm+SdJ6gAP7BJZssrL3HJak+PH5Lg4mY/aB5U+qUSkNq/BRZa140z2BUiXvdW0K3Nh/LBEgdGiwTuj/rPpHNTTMSj8rM3wCtRxrJTdvqNdYLJocqAYTjZ/Vl0yFJSD1IQW1lOhF549F1Z+HtdILjmuhMhEhK3IyYMwUdooAAAA==",
  "alt": "Aerial view of an industrial site with clarifier tanks and process buildings"
 },
 "aerial-river": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#5b6772",
  "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAD5noHLf1W1o2+IgVUOAD6Nlv47WvakSnGr0uqfJiQQcQfReVyl3KhqPloHwP/cQWT1z6QR0rpRhs9L3yPPE3PTeLrEeYY1NOybyx/kNbBIm9VzG1ULgGoZIc1swcTRxx8v2Yx6f/9+LxZChTffzH3E4e37QMQAAAA",
  "alt": "Aerial view of a clarifier and buildings beside a river"
 },
 "aerial-green": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#4f5b67",
  "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBQCdASoYABIAPu1sq1EppaOiqAqpMB2JZwDOOA9H5r1oZBejucAx7WO5BJR4ye0egAD+cZlN2KTmOXtw2AC/5FwkDhW6Mw3+JffGwBhMPv/RReHy7DnRcKvx2LxddS8sidXZx0gNtql4Ffqs7fsbN7Shha3btyU+28zjxp+DOUqtXIorQAAA",
  "alt": "Aerial view of circular tanks within a green field"
 },
 "aerial-bank": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#636e79",
  "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JZwAAVI/psJGWGw9qCwAA/sv30zeliKgpgyeDXjCfZ+aLMnY4CPauYuyRTGGi5ZJzTLVj2iwX8QGhZbKV3apb02LUUMR2vUqhkiJW4s8RuUDyud5ZxuGLALO0o4Iohyt5oA3Nq76n/KE6KmQ86QGfRAAAAA==",
  "alt": "Aerial view of a treatment plant beside a river embankment"
 },
 "riverside": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#6c7782",
  "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAAP/vUHV0LRJHGqR1twAD+qGUU/ubNqMOrkhS2Swc14laSgXAjH/J9QKFO0gV5/PvyRezcyM3SJ3SYJ1T2I7XnI6DMhvc/RWhlsjtSacc9MrlTN6WW4rFqDsZDeU/XKsvVx72HEts5EPHOUGGeztDfonULQAAAAA==",
  "alt": "Aerial view of a riverside plant with rectangular settling basins and circular clarifiers"
 },
 "clarifiers": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1357,
  "bg": "#5c6670",
  "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwCdBagR+ooHSQi+WVJTrloTvAAA/rocH8OuDAnGDa/eg73yawJ6ZeUFw7Dmb7Wz/79/4ut4LQPNFfcUfhozJK98auZISX2Sk2pwzHT0CW28aBgtRckPuLtqSSc9RI2bkRxjqmwRh0ZhA/kcSbcMwJfyuO+ys6a8h64c0N1E+LZ41StAbfuEqP+3cEDgAAA=",
  "alt": "Aerial view of six circular clarifier and settling tanks"
 },
 "clarifiers-twin": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1353,
  "bg": "#4f5a64",
  "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwC7AYv+3nzr4remDxL5J5m2AAD+M7B2CIVhraHh5e8mNs/rvMYwV23GzUGrdQP4oNYuRVqEbyqRjsLPs4i+Qhh04u7eskyvXGylvkFZHoRZZFCyGiOA6ucjzJMIuyOyXqlJO4Kw+sXQAMOP5/Rn/4raJ/x2gs65y83SxsNhO4YB+WetvLuQmeu9ulLm1SjwChsSM4sKAAAA",
  "alt": "Two circular clarifiers joined by a walkway at a hillside treatment plant"
 },
 "clarifier-teal": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1124,
  "bg": "#6d7680",
  "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JZwCdABuZI14uGPgs0AD+4kSaXQVOrmg5KGBHGv6ksyStO7y/Z5gvgPUpRIHHyo/3Qs9MKKlqBEzMo74ZJTNAgpoj2PZ2wDLCrjB22FvTdcalvwCKyj7BDBcrSER2pEXxW9fd2HbHUc4eDnj2gAAA",
  "alt": "Aerial view of a circular clarifier with a bridge arm"
 },
 "clarifier-top": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#67717b",
  "lqip": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAABQBQCdASoYABIAPu1sqlEppaOiqAqpMB2JZwC/7Yxia8szpp5r+2tECNjuCl3DS9ElHAAA/gkLIvqqlpOuZ0vJ3SMwiSWBxFSNTvyHqLlLozTVKaBg9AVwr1Lva6qs7xz3fpzsbunat900vBXUDLUwe26GV9PfxZJpnPgqEucvBMmKteNiscHzlkypNcFG/oDiKDwsPhOe4CxcEY2KhoeuVxpDZtg+BgsqzmRAg+vMpOOUFaG6qWkv75eyfOdQAAA=",
  "alt": "A circular clarifier seen from directly above, its bridge reaching to the centre well"
 },
 "clarifier-detail": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#5a646f",
  "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBQCdASoYABIAPu1qq1EppaOiqAqpMB2JZwDMHYv+cVq0W4narXb3zcqo4LSVFivgAP69E0PVuCRKUaM6JPDBlZRM5HDkLAte0ABxRh8RrxJuJUt6F+YxjMu9wCGgKgW08zDUX0ovf57N1byXmBzN+sGx0hKE4EHvgvHBiE9tL4Q1/Rb6mwnCMWkyLaOSVoYxvPcYXBsmgAAA",
  "alt": "Looking straight down on the centre well of a clarifier as its bridge crosses the frame"
 },
 "clarifier-snow": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#78828b",
  "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABwBQCdASoYABIAPu1sqlEppaOiqAqpMB2JZwDNwy6TogVz6iDAsCX1HRyS4ghUEpK4GDMAAP5qeK/ZvPzUJMWps979L8VS606nc5f2OHVRquFS2sw2xkaxfFvs1aVrNIm3j7wrtkHRG3anZz430hO09s7Ni3p50GltM15pkFHCfmql3JUp2I6o5PtLdaVEw3QlmWfnKNVHbje3igoxDUgBoYajUpcTA9oWrq0SAYfJ0uIKUEjFr/lr/eAAAA==",
  "alt": "A clarifier in winter seen from above, a dark circle of water in a field of snow"
 },
 "aeration": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1340,
  "bg": "#727d87",
  "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwC06B7H3zH2cpLVGD26vzByAAD9SbRUt91Z8W44dAYwvA+0WSX+hSVwU/na2KL2K5K0QoQL3qVrMmTp2twt2EYjpCd+WUAmlnQHQrTGml7t+r0wz8I3wcOGiSQzekSblJdENgdSmIV6AIAAAA==",
  "alt": "Aerial view of an aeration basin with bubbling diffusers"
 },
 "tanks-grid": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#5f6a75",
  "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYABIAPu1ur1IppiQiqAgBMB2JZwC/PagAyxau8Y6bxaK/YdBPcAD+hX88IWB+agMiDKNieeq9Qc/RkKdrc0wFI9lrB4BCtFrrA6krT6JJq0ymbdpNTlXTUizGEUfc4klMIwIysMI0+luS0Aj/hybFQ787XX2PqJh2Qx1d2FFTJJy00Hzo4usaFaIIKk2BbxOCNYu2jalVYKqXJFgAAA==",
  "alt": "Aerial view of two clarifiers beside a grid of aeration tanks"
 },
 "basins": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#616a73",
  "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAAAwBQCdASoYABIAPu1mqk8ppaOiKA1RMB2JaQC7AYxEXFOfaXI+eHHfpnF7XXjAwHL6AAD+wkm67u78dGGtWxF9YWRX0pPeLCKqF8gE1if0Db5sALB7vMk/OGb4/TJHXCxYIsl3FJDHLcNwYKQ6E4hLuSL3opWXAlib5KIb/Q2okgXXiWuw8WWcRIpqp3eqgZUvQU6wwjuleChLOypAKdjBMvFZGDyefMxRTingUMAAAA==",
  "alt": "Aerial view of aeration basins and two large clarifiers"
 },
 "water-caustic-dark": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2093,
  "bg": "#3f4a55",
  "lqip": "data:image/webp;base64,UklGRvgAAABXRUJQVlA4IOwAAADwBQCdASoYACQAPu1srVCppiQiqqgBMB2JaTuAIB86dRLcT9Q9Vve27xKRCz9ZrAJw8uKGMIw6QAD+40ptP2Qce8eV0I9+kQD/Zl8jbD1TLWAa/X0oQYUq+apuLtl+C6cvSF7hJX0ssYnPobewYHBLXuDvRBu4DqQmhQMOxng3zDnlqeg8VIBLNcX3SNEUPmCJDIqK6RpMFH93wEwkzTMFkoUz5LyeBYYfrEoMw+/d5iHGUtQCprUUREWAL9F1tz5zqEpWeaZigpa2IuSEi55jmd2j9RZD3Zt7mj+odG24gqltPHY3vEjFBdYAAA==",
  "alt": ""
 },
 "water-caustic-light": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#64707c",
  "lqip": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAAAwBwCdASoYACQAPu1mp08ppaMiKqwBMB2JaQAOf3YvKB4AaaFooH2LrKlpigiRNVdh3YUt+j4qS4gJmPcVzgpG2AAA/ocO4vjNkRc1U3UMQLO+YaSH6UYxHUARjk0JioL1G8ABKs3em2xB9Gu+YgSbnpn0Hyt2ByJh8DeM49zeJnDPxjZjd9E8cR0jIlVWlkChWKI9qG3FPnaVmsf4GNteM0fSX8DdqrxAuk9ksUPXSfkCrDlFX2wlUHpqarbkXj3PS7CRJzED4I5HE9gQhrmbFyo6yBVfTnAihi8apcAmKCD4qnvHrRuJgpBLxdlTVAdhXRzd/t4oVgAAAAA=",
  "alt": ""
 },
 "water-caustic-sand": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 1640,
  "bg": "#5b6772",
  "lqip": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAABwBQCdASoYABwAPu1qqlEppaOiqAqpMB2JaQDOPavlG5wAA7Txbcy1UvtcP8hCaTUHn/pAAP002SCG1k34ONCa+AiRJLuoKNMSuBqBhTsCnCc5sjkVgabuWCnvKtNM9D0kAddGhghPd0MWzJ1NZwRLNSBfsLyFa6w49prTucnDN7+ywcQSgT3K0zi6TWz2OXCmu9b6C/n0uaos2fMJt3f6cMYqKMQ5KiBGBsVGkoPR6V8kr+G31Px8N4TjmIB7TjRPuGiV1iHQAA==",
  "alt": ""
 },
 "water-ripple": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1335,
  "bg": "#75818c",
  "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAOcAKULS6y71hlR1MAAP6TfqDEG7Y/pIZrP7oOBCxCjwix0fLIQePR22iJVJhNsSBNz03ZpYfWoUYRcuTbUsWHo9A+HtU+psrWH4KMZNuz9Gc271h4TF4fRI1eh7rYi+74eLe1iy+OX9N5AAAA",
  "alt": ""
 },
 "water-surface": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#747f8a",
  "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwC7ABKbBkiQxocCqADg/UmD6FeF8JgjPezbofGuX2bn4/jmQ7n0rptEQfLG74R26/rWVLlCrJsJtF7nKUGUQ3vhpRO9nbiClHcxBB8Uu36Irfm3sACgAAA=",
  "alt": ""
 },
 "water-night": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#3e4a54",
  "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JZwAAQtecrqQi+SguLgBgAP7kG7oxyVtfbSbWtM8RNz02tf4whAU65NNWvcise0HE31s7XFO1DAULctkLcl4AAAA=",
  "alt": ""
 },
 "water-dusk": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#4c5761",
  "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBgCdASoYACQAPu1crU2ppKSiMBqqqTAdiWkAygKvAD4uVbx8DZpdxkwmbo9LjczPb54eHrhe1egAANnKtQ9vwr1tjCOiQPr4N3ipb6gyC+aAb/SylhtBNMFqY/5ARFCtwydA/I3ewWoEEkHxIH4Iojp9fe5/qIBTGFdZeVnaojkInal93JDsOCHpiDwKrZD8OAH5ge4AAA==",
  "alt": ""
 },
 "water-deep": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#343f49",
  "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACQBQCdASoYACQAPu1wrVIppiQipWsxMB2JaQDPZC6b+brxPsqnrNEXZhe6Hcu9Rw1egadV0AD+9o2vDKQwxTfHL++u4GTkdoFAllF73s7uNBIyoNWoJZBN373HaVTcW4uqBDjGiRvDiLoljGgk1g3a6Sn5HYS1qwhUYyBGbUeLGL+n48PTvLGv4NIe8lF1vTGPTBieVNjrmrEDovES/tgAAAA=",
  "alt": ""
 }
};
