// Generated by scripts/build-photos.py. Do not edit by hand.
export const PHOTOS = {
 "operators": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#453d34",
  "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBQCdASoYABAAPu1iqU2ppaQiMAgBMB2JQBOl0AtwYQAcwAU5nL+n/4C+9DgAGaAiM0IAAP4IbG8eY0/eNUqi81KWpgTaIUe39oUSlaWdEOj3UlADr+3mB7Yec5DDpdPt86/1UdGs3a+rU7C5Ur9EzXIIoF18Xzp+Z4wufH3Iy+FQA1c3SQ90RhfyqaaPcZX9X3HMoYKzbA7Br6oAAA==",
  "alt": "Two experienced operators leaning over machinery in a plant, lit by warm window light"
 },
 "hands-valve": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2488,
  "bg": "#584030",
  "lqip": "data:image/webp;base64,UklGRmQBAABXRUJQVlA4IFgBAACwBwCdASoYACsAPu1op1AppaMiqqoBMB2JagCdMwTIqELzAHlkJrMasEiQ0cpAfyNbSsuQvoXR5Y8eqkBdfmPXzuS7YaIAAP6mrxsaGJwcFmT6sOpsOzec9UxSPBa+QpIFZ9iCNZufIO33Lk+HrD7p86mx7yesUux/cnUrbjfkMR8u0YP/aOQYuo6PAd1loketQvZsKM30IT6IRCq6+U4WVbw63mdypnoINj9ujziH4jlKykddXJb+k4xVVqInNdwqsjEQBzv+LUnIfDVGKkw0jQcGhGYUk9hlVcm+2NPewaq2yqv/1cARWefZqGQkqSpoIghCNBrpOhUfgYfkDFDXyJIecYZUyVdXdRk1+kf3rkziwwuLnGlBgZB28jXJdK/jHj6WTFJ7J3IjPUkJ28r2rU45SsxtwDnQ41F4L3ybFUypQMx+5g19TAM0wZjUpcNKTFtNoAAAAA==",
  "alt": "Gloved hands fitting a valve onto a water line"
 },
 "stairway": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2096,
  "bg": "#505253",
  "lqip": "data:image/webp;base64,UklGRiwBAABXRUJQVlA4ICABAAAQBwCdASoYACQAPu1urVCppqQiqqgBMB2JaQALB2d5EZ1phNcZ+jV4qQteLZ6v3y+SOvYVH7wa/nUDXCkTFB+uAAD5a9tuUR4nqfUG4qzjRZxgD8ewTOk2S3FCNfzL8ULjV81eDfB9kyh/82tm1u8P9DSObj8nC85tyhW2oAwRXplitCV/Ynh/wuf6tfwyNWaq40d6K/au4zJirbwMhYN7qFvW+HH4Fxx6xZ6jCX/7FO5ynHmLyJ68KTSfJtTUKR+QZ9D1ImDSR3wx3U3/P76F/KwOHnmTq8cm/QoqRxlxdgxBXzno5ZFEsFw7kTcb7k7wlKZbtWce1w72DZi44gWlNnQ/WQf6v/P9tXJUGYbh3syjz1jfKIuCVAcYMswAAAA=",
  "alt": "Looking down a metal stairway onto circular clarifier tanks"
 },
 "outfall": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#525a61",
  "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JYwCdLwAVf+3EFf5HoZchBa55tAD+0LZ58hETu5DQURgOs0F+7xyq0qtuNcF5t8lgaFWabc++WQDqSGXEa3QZkojnly5hGk1YkMbMPQNL9VWnOnkqMBRoklBgpUZi1SUaySWzouv70Md9nRsvdjvc7HaNHrhiGAAAAA==",
  "alt": "Treated water pouring from a row of outfall pipes"
 },
 "plant-night": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1335,
  "bg": "#343531",
  "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQAD5CIM9ngpvOtKa8r1pIAA/vKfT2Wc5Su0z5k95bxaN0d7G7W50yJDrCIH10b3rVdHfM3XWkJPtBvS62L9qdKCWFavn5ut260C6AyIccotlMX46w1xnht/scq/xREBT168r7hh32RlnaWsx2DX6BnfeGg/GjyTNyy1/P+oBMSLImYNHPzvyI1PGN+TrgHBDQUtwShyAAAA",
  "alt": "A water treatment plant lit at night, seen from above"
 },
 "plant-fog": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1332,
  "bg": "#6b7172",
  "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoYABAAPu1iqk2ppaQiMAgBMB2JZwAAW+hCIDXrn0DrIYAA/u2tE725BcLqhcQp7F+GbWwn/MG/UGlQxZoSzi0IwzhYXM+slbfPRrdoyZs9m/JFGIfNyUDuHoyJ36UKoecFCMMoGyAAAA==",
  "alt": "Aerial view of a treatment plant with domed tanks in morning mist"
 },
 "plant-bw": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#626364",
  "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JaQAFEB7q0WtYL0qpCz397+AA+wXlkgD21OCCuLIq/zbyM3DLSCq1n9jcPpA9gpJZSgrpvZrKSasiR7ElUCZLnvXjLuOxCuNoJH8WQkdn/G6DxHUXvanjbp5OWI22hjeaupf+5skIwf5wNj0GYF2M5IVS59BeYB4jnEzCsADZwIAA",
  "alt": "Black and white aerial view of a large treatment plant with many circular clarifiers"
 },
 "aerial-rust": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#644943",
  "lqip": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgCsAYx21ZT3Xs3ZWZKjPdE9WqM4AP7RgTCnJZ+4Qt4E4vADAj06pzephr+FBeqroyvF0v82/g0W/jqIxaK+HmccedUCr3spNVKo3GxV1zel7DbN/VcOYaDSwpJD9fXgJE/pLNryAuzW+dO51lWibZz0A2f9jayPKxexA52b5iq68aY3TFyqglU/+aav3iIHrTUuSp0erkjvAslHYwr1+WBYLIcAAAA=",
  "alt": "Aerial view of an industrial site with clarifier tanks and process buildings"
 },
 "aerial-river": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#646952",
  "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQAB8pTcaJFbZYzBRCWcBMAD6NldM4x77ZBupPdgKiHZCmx/BGxZkqYy2v0rRY8Y5trR6E8SUv1VUfvqfGlrlQE/Bs3j1hDvUwZZ/PU+6pNM36Ne+2QMdUBqKzxHKf3PLZ9YRKhy3OCIA8wB7/1IHugdSSFL3fE31dsMbISk2SzyGz9a0eTAPRdUknJ9wAAA=",
  "alt": "Aerial view of a clarifier and buildings beside a river"
 },
 "aerial-green": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#506542",
  "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoYABIAPu1srFEppaQiqAqpMB2JQAAFOnMno0Zye3sE5wwAKuaB862QAP59RNKCbs6nzQaXg22tffhIHCt0ZRpSHFJvsqMOKAqsi2r9yo0PIvO5Ydt4ksZ8VZpmlQOydrPunLs1GNgHqEbG1TSH4OKyU1g/Y9fOAe8HtEUsjLPIkxzYd4qPol7KjYHXMpQAAAA=",
  "alt": "Aerial view of circular tanks within a green field"
 },
 "aerial-bank": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#73726e",
  "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZQDE6f/gMO2qdPcT4fTPL4fgAP7L99M3p5DN8HrEq639u1Vm2xHPN1TscBUFpt5EQN+1s7ZNskxBsypuD1FPDp+Y+d1zv6dYsZwLmTXT7RUsLTBWoUtwhihj/uzD4hK89zDV2aVM0ZkO0JoeRcxy2F693vKRdi0b7GqiG0T6zx+I2U6lR5mAMNZUF5AOIAA=",
  "alt": "Aerial view of a treatment plant beside a river embankment"
 },
 "riverside": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#7f7d7b",
  "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwDKEf/gO3fksubIzWD7YqooAP6Chp4jkCNkhWqsJp3/h2DOd6+QRFeBzv26KWaFv44jqFh0xMoA8l65CPCX8h5eFKYyd2fcd7MgVVkcKVCW9gOzIm1l7K6/Pe83d4pJapvBZHrynQGNaocpEDKiqOPLO9ujtKv0syuxlBdGvbR4Gl8HEAAA",
  "alt": "Aerial view of a riverside plant with rectangular settling basins and circular clarifiers"
 },
 "clarifiers": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1357,
  "bg": "#676968",
  "lqip": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwC26ExqQPcsY+s/zLRp7S6YHhwA/r/BX6Mj/untKWoZTfzN9OI/VbASkc1Ec8yRocHBUdeCygjBT6ptaLJcP/S83yaMv3pQNS+14KKC8omLlevCKiFvEHlRdBYsVgon2YKvON6Jk1rf+FgrPYe5A6faLNtUHSGyrWWS9HWL+Lz9UcDIk7cgd/nwMHJdOoMkYiouojRMCHS6S9hQ/yHw/FkzXF5BAgAAAA==",
  "alt": "Aerial view of six circular clarifier and settling tanks"
 },
 "clarifiers-twin": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1353,
  "bg": "#4b5c54",
  "lqip": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbAC7MoAvQTOowV+GXdlW8Q7+auHYQAD+flWpsMtM2kts4/aMj4fAy2PIHKmuwzQioFHWzQnP9WXOIBlTykVQ71twuytir98k4+JktqYWufJs4ORBwqd+nQpS+TNqMVfRSir3NFMHo9l0NjPMmtzhDjSS2UF9kARgj5/JcP4grq/X3HcsLk/X3kbvTiKkgRZVJboxn49NxmIea3aPIuFJUIxW2KwFdle/wZJhRVo3jw8zR3LAAA==",
  "alt": "Two circular clarifiers joined by a walkway at a hillside treatment plant"
 },
 "clarifier-teal": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1124,
  "bg": "#847769",
  "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBACdASoYAA0APu1iqU2ppaOiMAgBMB2JQBOgA3Pvlo9coOo0RTepvAD+6IzCp/EZdD1d//IDkYgHvdXksU8O9JCsuAtSQkgZQEGAT0fw4suLjxX1BBsDcSM0RXOie3cE33srRINwi1ch153/ga37Di3dM/TWiodT3axsGBr9cPGmJXYIm1rRkDDBwYvdmQqGHJ10JOluRGQRUAA=",
  "alt": "Aerial view of a circular clarifier with a bridge arm"
 },
 "clarifier-top": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#727368",
  "lqip": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAACQBQCdASoYABIAPu1ur1KppiQiqAgBMB2JQBh0UAe1ZhPjZK2uwHaMEmmm1niJ2GiezKxioAD+CQsc3Dveq4fPrnw1zm/i6h3LW4uZGHsLTcNQVISFmE+C9YvQWQCoJZd0EyVy5DOTD+CPgC9AROG3yRI251z2qGwukgd/48vPePYA4Q3Gw+QPBOLkbpYa0t+kOAq2yhph/ivIngRYfh+f7gxij0Gam1xpn85YC0tl+q/DhkESXJPa2VIg5SiBg3aOelytgMSA9UmSjbuIAA==",
  "alt": "A circular clarifier seen from directly above, its bridge reaching to the centre well"
 },
 "clarifier-detail": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#63645f",
  "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABwBQCdASoYABIAPu1srFEppaQiqAqpMB2JYwDCgYv+aGZSp76tdZA4BAJaRlQGK+If1oAAAP7Oweh7rmCgXPLFYOBXY5prhfYMQTU7k/XZz5UMCtUAaxtuyR6UZ7WF+KDPhZaszxDVUZd3t7f978RMjPUJUD6RlncKEoyRvZzGhZMzsptYFiuYIgzP+oBloNTiRF2ZO+HYpI6KT4f8HkgapMDHbjfdSb8TWIWeAAA=",
  "alt": "Looking straight down on the centre well of a clarifier as its bridge crosses the frame"
 },
 "clarifier-snow": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#7d868d",
  "lqip": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAACQBQCdASoYABIAPu1urlIppiQiqAgBMB2JZQC7M1XlvArn3xmpNFRZaroc92m8HJsbdQYnAAD+mpGrlpqO8L9AdJg214S1VHv9p7BL/Y0+1ZobM035FE8LPeLMCprk6zAsgmDZPTJAPCZJ6GNFBd/kHEl/nt6j6depwmZjnsri46HWZ6o1e1sb25HZS4ha6BS/BkKJUoYuuB/0kJa1yMxCB1UpvOglQPaup9PaGFMq5xMLyV+dRcwnkyulQnYsiIJEcoUFcxW82V9Z0l/xDv8AAAA=",
  "alt": "A clarifier in winter seen from above, a dark circle of water in a field of snow"
 },
 "aeration": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1340,
  "bg": "#7e8281",
  "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACsG1/AWOPk8so0f8fwddvya7VYAP1JtFOSBm9DTex2cNgiBZkzNGUS+ts67uO2L/NTRw0c5+EHPQzzo7pxOg0Z6DwsvvEpFaLKdvbralbT4nK0J6G14mLDaXCVOSHFV+HOajDp8vBA033ZEZ+QgABfeUwNFAMNrdifROxhGLp2fAAAAA==",
  "alt": "Aerial view of an aeration basin with bubbling diffusers"
 },
 "tanks-grid": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#666a63",
  "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoYABIAPu1ur1IppiQiqAgBMB2JZQAOcC0dzd1+0zCtGsDQgkMwxfAA/oWBaMJEYYiIURU8PkGwteA1QHLXBN1yUVm/n/8UxwgglJ73/TLeBxHpxY+02jkS1YdhjtPyUU6S9KTwuC915wiReE31fV7jeXDhahfiwEqwlkqNkFavnudnzZkKYbe7AU9jfw2NwfcO2K8J52fAH/gvreTrlJOcpKhOm1nAAAAAAA==",
  "alt": "Aerial view of two clarifiers beside a grid of aeration tanks"
 },
 "basins": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1500,
  "bg": "#6b6a68",
  "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAAAQBQCdASoYABIAPu1mqk8ppaOiKA1RMB2JZwDOdYw6Zcp99CKHKUDMogwwOuS53xgAAP7CSbru7gR0Ni1D1rcdUBM1RzV/apisEFVZ1vwPxE1Pu7lR/Skf4Iur6A2/JKJUm5zbFVOFnTzrwjEje0COE1U7pSNA4J9Jk+WZncH42fDvTSJHwbkIxsnJUuiffFV5gU20adyWsJQ3SSLiJrmMRtQcTmu7gbAuCowFCLz1ugUQPG4IitoQZgAAAA==",
  "alt": "Aerial view of aeration basins and two large clarifiers"
 },
 "water-caustic-dark": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2093,
  "bg": "#3c4943",
  "lqip": "data:image/webp;base64,UklGRhgBAABXRUJQVlA4IAwBAABwBgCdASoYACQAPu1qrVCppaQiqqgBMB2JZxwADcvKAdpfaRxNHeyJMlkiBrDWO+LzdBD3x6N6sc/ndYAA/ujv3YHCeOQrK7jDuLnoLUHS7SgY/bCnLikO9vXa5EHC1bLJX7gDu3zSE7j52yye1XPK21tDv0OJ3kZ5C9nfGExMNAoNQAl3flnCVZJRD154c5OKbqsH0Qiw2Vd8+eBi9Xf3YOfEAQUNyYy24UTzPESMjYozCg6thUJx/RkrTmJzCpmc3ghZNB7C4wY2S3H4Qrg1T1w+AhJN01wLjwYr+TMn/Xmy2iYeFbrl8xsKqUgkEr4YoTQ5aVLIBD0E+0KJNP62TaVuqIYD0PAcYAAA",
  "alt": ""
 },
 "water-caustic-light": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#617f90",
  "lqip": "data:image/webp;base64,UklGRhwBAABXRUJQVlA4IBABAABQBwCdASoYACQAPu1oqE8ppiOiKqwBMB2JZwDG+vF1cs7csDTMNKBaLrSEQuyW9dPgdNL4RIhZ5iZ9hQKzbTDLM5YAAP5II29BiWHFFavLESE72f3FSMvWlUYnUHEDqj/8T8xyN/r895oLxtA89tk0Oc7HuD3N3tHgJ9pxJZYIpksUVnAr5Xe9+N4dytA6XpS6GXvqhiRNhDt2NNz+OGdmCY8Il3siF9ZGVmMvBHHzFOqlAUlvqI8OIt0OXi4JDy4kZmTbdcgHCynfTDd9pCRwlpIJ5a0lMvyMoqFEKz1KsVObWnmzGRJ6ElONemwVycVv9q+mwUEAmv6Q65/cS7dMglmDWvvPa7GRQQTvA4MAAA==",
  "alt": ""
 },
 "water-caustic-sand": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 1640,
  "bg": "#796d4f",
  "lqip": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAAAwBgCdASoYABwAPu1qq1EppaOiqAqpMB2JZQC4raglLJqGRPiNwOMzCaFbGQPIK/kLhQfCN5YWTnAAAPQ5oIpSPh4V5GVC3ctFXBoa2otYki70rSCZEOUYRs1tW7BRWgBiMNaCK4+mFpmHkDaZKvC+kEi4b6Lqg3JNU5M8XReQLGVMgfYFMPa/A8NJOJfkBRWR6GQfe9pSOieH0DaoYHNp6pD6/9wWPForvNoB4nxlHL73MmQofn71HVhjFF7SM5azSTSj9CCfdijgK7n+ju4HtQxw+e+6CfjyqynncwAAAA==",
  "alt": ""
 },
 "water-ripple": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1335,
  "bg": "#b17d51",
  "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoR3BtABOEhH4AxPGbKIgAD+s0ROmvZaNzIw/adBkYx4HKQhmGfLIHYTSHN6OwcPPuW2u4PV4r5M8o5zOgjwA11MYk8jaLAEGJXldMK1PCuNnc8f/9HFXL22mykE2EMPuWfoKAxZvlBI9v7ZOm4/MO5kD22ysgU1tWQMgfPBTngAAA==",
  "alt": ""
 },
 "water-surface": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#61858c",
  "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZACw7B2hoLM/z05RpCtwAOD81JQKZNnSwD3OYraWfTgXz9driNQ7JecujebC0iGdfIS2CrXgBLh00V6hdBIVza4ZZgGREwMqFuRR76jCSSu/cIJ/DOG5PVPsq0+onL5AAA==",
  "alt": ""
 },
 "water-night": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#414849",
  "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoYABAAPu1kqk4ppaQiMAgBMB2JQBOmUABNdYQ5CtvP957vwAD+5Bu6MclbkelG/Fk6yMtPrS8Ru4R/D7P6N0TJMOxGMfpaXZMA+MWfUhrH+YRpXGJC45ElkRV7GnEJsZffIAAA",
  "alt": ""
 },
 "water-dusk": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#4d4e5d",
  "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBQCdASoYACQAPu1iq02ppaQiMBqqqTAdiWUAwCqv8FBIGD2w8+etfuPRSMKbWDH8eB1A7cAA2cq1D0b1B4cMVEYro/MUbfLS8z7rTDRn4YrkiSuLx4DsKi306B+a46b0ECkuQ8wQOE5RyA8NlsmL/scA3u6n5ao8fetk0dXj71bSTmmNJLzvazLz+WLlWirItUjcfnmGHDAA",
  "alt": ""
 },
 "water-deep": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2100,
  "bg": "#135a48",
  "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAAAwBgCdASoYACQAPu1uqVAppqOiqrgMATAdiUAY5lXaHBTNy4/nK12C/gi/zI6URR3bc1+vRnlgqs0gAP7yqoVXBFu+YmJcjw7vzs+BviwYfEkT6AjuFPsVJnpp9Q5C97DkEHgB1KQ6Hw3SA11DFkmO2TJAlnG2+oBKFQMngRYMlGCAsaOtIaRR+ewmTOTdYkZfOjMdwAO4nAAdpqBjWb3VByV0Sn2ovuGAev+e14puhe/87s3kLIfcKVswAA==",
  "alt": ""
 },
 "water-blue": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#294e70",
  "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdMoACs/kCoXZZ/V8NAAD+5bp+cwxzwKXtHP8N1CuFzVoayvTasHvACA3x9ty9BTrZ0Ef21d45RYUikq94H2mEdjTdq1nMq3Wvh5mh5o0FiVOWOwvGVaQP+UUO73Fy2Z8QiZ8pdWt85jSylXelxB5hl/xe1LYgFTjBMQAAAA==",
  "alt": ""
 },
 "water-copper": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 816,
  "bg": "#7a919d",
  "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoYAAoAPu1iqU2ppaOiMAgBMB2JQBOmUAA3AsPTAiFGjBAAAMm6QkKHQKQpGP2SCr2j1wOAboBNIIyCJI8m7hivAhbbksSsYc+/MDe7gkQRBMrVqhgXRiEj5AHHhzr2fdnKHOJAxvYBapvojAVNO4AA",
  "alt": ""
 },
 "water-sunset": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#3e5057",
  "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQAALlf5LKy5qJ+jNb+c3gAD8AovmWpDeZfl796iZMGib1jsMhyje2xQ/b/s5Adzj5/mXiAUeExPnyNV4j6A/81ibCi05dx0nbkU3rJugky/OECKAAA==",
  "alt": ""
 },
 "ripple-rings": {
  "w": [
   640,
   1024,
   1400
  ],
  "W": 1400,
  "H": 2097,
  "bg": "#87a4ba",
  "lqip": "data:image/webp;base64,UklGRjIBAABXRUJQVlA4ICYBAAAQBwCdASoYACQAPu1kqE8ppSOiKqwBMB2JQBXJ8BnJ4lYYGt5Tw7DNFDmbRCITzawBzK1dmqjXoFz3lOydOOLZaAD+zEq2DOfgWduu9aGAbDmE9aOhDyXol8FUFf0+r4PnF543XQ5IojRtZE6QTUBYDkutiF3TLWTWPwLbFB4igi+vBQ+q1VZ6dR9owyha7e8nYVNaBgpBQs26uRof/vVyMSUGctTwwk/5oxAsPqpewavxbxMB/Df9MTDeXxe/UpZSizRv0MJMT4vkpLridXjVwTFq94TZCPSkMxU6SbrrDsPtM+IU8YrV3/ASZRckP/4R3oGdhNpvlXcV67bas4BrzMfRioepjVfNCjVrr327QvhCOMaCAv/jL0T+mFk0rKQkigqAAAA=",
  "alt": ""
 },
 "drop-rise": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1126,
  "bg": "#314247",
  "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCdACHfaZ2VIvUCqrT5stAAAP7wyQjAYi3KdHtqZBxnftzDe4lQXUk6lMvYKlrYMcRdVaCgfMekUi8wmuewyU7+iaZXnbyks4Yhl9p/InBN6hRJopAYRSHm6e0S6rvfCI9SaLgHDAoWCZtN7jTCd1Ev1hSp19AC/QAA",
  "alt": "A drop rising from dark water, light breaking into colour across the ripples"
 },
 "drop-splash": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1126,
  "bg": "#2c3d43",
  "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZQCsAYxs32xNlkixbHWmrUwcAAD+8qJYi/hspiDdwhs06I8tTHTYmm2w4nQ7YqcVIjwa7vTXnGQicrIUv/VsJBjrJ/O/rFefS7syKMnsn+A5aIWK1D7/OH+Q9IRySp5X87qJWriXUdUn21214HPDPuBaCLi9F6gKuhwAIZuwAeLAR6kAAA==",
  "alt": ""
 },
 "drop-mono": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#acc1ca",
  "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JZQCsAYwwyV8kK4MrRXoWhmBbQAD+50E2BWnO8Mkb6Ajx7luW/tBd9+auJ/6x1vEjYSJWqTXVORapSyeK3ca9miTQYbhXSnOJK3W7a3XkoT8Jxbm+DpTDp3H3hw9kQbp5VHssfftttu8HHW8j48MFlaJMSYAA",
  "alt": "A single drop rising from a ring of ripples"
 },
 "drop-crown": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 903,
  "bg": "#5478b6",
  "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBACdASoYAAsAPu1iqU2ppaQiMAgBMB2JaACxG1ABQT2BCXVzau+YEAD+FaOXLx8qHG1kUlUc3xSxcMand5wCU2pIUf5N8A5xk0YS/NZDFPxpAPtgmi8ssM2b6rM+SGv94eJC+fJPerFI4gnrIPoAAAA=",
  "alt": "A crown of water thrown up by a falling drop"
 },
 "drops-falling": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#123d58",
  "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZgCdMoMxgEmNgFwuLGPDHYAA/vQf7Z+yQBMakE7vPke6BhrBXDxyys2gXsnA3y6jC+ekwT/UsRLv8vHGdI9FVwLBTQFvSAA=",
  "alt": "Drops falling in a line into still blue water"
 },
 "drops-falling-2": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1333,
  "bg": "#123c58",
  "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwBACdASoYABAAPu1kqU4ppaOiMAgBMB2JaACdMoMYORVtACB/Sciu5kVn2hV8AP70H+2fx5C5WfYGD9CdL31u/gj40vx6tJ4e1XSnkRFVzj8g8godqdhJjueFpHvjaKOw/hTRwAA=",
  "alt": ""
 },
 "glass-layers": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#c3cfe3",
  "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACw7Buw6xOVlNLzJrkJvUAA/uf114p6lyjHe/IJNUeVAO9nT2u98V6y/b7hxGrj811jHBc0EBDO6FraWpWyNh2LKlveM3kRlsEfIpLlvduADalANXJZFCHIswvARwARayYAAAA=",
  "alt": "Layers of translucent blue glass blocks stacked in depth, an abstract picture of a layered system"
 },
 "data-terrain": {
  "w": [
   640,
   1024,
   1600,
   2000
  ],
  "W": 2000,
  "H": 1125,
  "bg": "#8088a7",
  "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JZgCdEf/l2AIVJzxWh1dgwCUwQ4AA/LHQcbQDb5W1YP4ULSLqOp+DRN+Kx92M6u0jyFtMchXsy1n4TQjpblk70XmMO+/U5vm7zPvwcPsUBvvnUB1rii0u/MqgWKcKOwHIzdMmc55jGlvZGUTmAdBYSBEWnK7TRmkGcmqDV048zjiAAAA=",
  "alt": "An abstract landscape of thousands of small columns rising and falling like a data surface"
 }
};
